// Generated by Wrangler by running `wrangler types`
import { D1Database } from "@cloudflare/workers-types";
export interface Env {
	BASE_URL: string;
	ACCESS_TOKEN: string;
	SHOP_ID: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_DATABASE_ID: string;
	CLOUDFLARE_D1_TOKEN: string;
	DB: D1Database;
}
